GET http://localhost:8000
content-type: application/json

###

POST http://localhost:8000
content-type: application/json

{
    "name" : "darshana",
    "username" : "darshana@gmail",
    "password" : "password" 
}

###

PUT http://localhost:8000
content-type: application/json

{
    "newName" : "Darshana Mule",
    "username" : "darshana@gmail",
    "newUsername" : "darshanamule@gmail",
    "password" : "password"
}

###

DELETE  http://localhost:8000
content-type: application/json

{
    "username" : "darshana@gmail",
    "password" : "password"
}
